name: dreambooth_joepenna
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=22.2.2
  - cudatoolkit=11.8
  - pytorch
  - torchvision
  - pytorch-cuda=11.7
  - numpy=1.23.1
  - pip:
    - pytorch-lightning==1.7.6
    - csv-logger
    - torchmetrics==0.11.1
    - torch-fidelity==0.3.0
    - albumentations==1.1.0
    - opencv-python==4.7.0.72
    - omegaconf==2.1.1
    - pillow==9.4.0
    - einops==0.4.1
    - transformers==4.25.1
    - kornia==0.6.7
    - diffusers[training]==0.3.0
    - captionizer==1.0.1
    - setuptools
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
